-- MySQL Script generated by MySQL Workbench
-- Tue Feb 12 21:52:07 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MaSy-HR
-- -----------------------------------------------------
-- Database for MaSy-HR sistem
DROP SCHEMA IF EXISTS `MaSy-HR` ;

-- -----------------------------------------------------
-- Schema MaSy-HR
--
-- Database for MaSy-HR sistem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MaSy-HR` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `MaSy-HR` ;

-- -----------------------------------------------------
-- Table `MaSy-HR`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MaSy-HR`.`usuario` ;

CREATE TABLE IF NOT EXISTS `MaSy-HR`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MaSy-HR`.`modulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MaSy-HR`.`modulo` ;

CREATE TABLE IF NOT EXISTS `MaSy-HR`.`modulo` (
  `idmodulo` INT NOT NULL AUTO_INCREMENT,
  `pagina` VARCHAR(200) NULL,
  `descripcion` VARCHAR(400) NULL,
  PRIMARY KEY (`idmodulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MaSy-HR`.`usuario_has_modulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MaSy-HR`.`usuario_has_modulo` ;

CREATE TABLE IF NOT EXISTS `MaSy-HR`.`usuario_has_modulo` (
  `usuario_idusuario` INT NOT NULL,
  `modulo_idmodulo` INT NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `modulo_idmodulo`),
  INDEX `fk_usuario_has_modulo_modulo1_idx` (`modulo_idmodulo` ASC) VISIBLE,
  INDEX `fk_usuario_has_modulo_usuario_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_modulo_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `MaSy-HR`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_modulo_modulo1`
    FOREIGN KEY (`modulo_idmodulo`)
    REFERENCES `MaSy-HR`.`modulo` (`idmodulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
