SET FOREIGN_KEY_CHECKS=0 
;

DROP TABLE IF EXISTS `SHSALIDASMED` ;

DROP TABLE IF EXISTS `SHENTRADASMED` ;

DROP TABLE IF EXISTS `SHMEDICAMENTOS` ;

DROP TABLE IF EXISTS `SHCITASMEDICAS` ;

DROP TABLE IF EXISTS `SHCONSULTORIOS` ;

DROP TABLE IF EXISTS `SHMEDICOSASIGNADOS` ;

DROP TABLE IF EXISTS `SHPROCESOS` ;

DROP TABLE IF EXISTS `INCURSOSXEMPL` ;

DROP TABLE IF EXISTS `MINCURSOS` ;

DROP TABLE IF EXISTS `GSAREASDIRECCION` ;

DROP TABLE IF EXISTS `GSPERFILESSISTEMA` ;

DROP TABLE IF EXISTS `GSUSUARIOS` ;

DROP TABLE IF EXISTS `MICALENDARIOCURSOS` ;

DROP TABLE IF EXISTS `GSPERFILESPUESTOS` ;

DROP TABLE IF EXISTS `GSDIRECCIONESSUB` ;

DROP TABLE IF EXISTS `GSPERSONAS` ;

DROP TABLE IF EXISTS `GSDIRDIRECCIONESGEN` ;

DROP TABLE IF EXISTS `GSGERENCIAS` ;

DROP TABLE IF EXISTS `GSPUESTOS` ;

DROP TABLE IF EXISTS `MICAPACITADORES` ;

CREATE TABLE `SHSALIDASMED`
(
	`IDSALIDASMED` INT NOT NULL AUTO_INCREMENT,
	`AFECHASALIDA` DATE NOT NULL,
	`IDMEDICAMENTO` INT NOT NULL,
	`IDCONSULTORIO` INT NOT NULL,
	`NCANTIDAD` VARCHAR(10) NOT NULL,
	CONSTRAINT `PK_SHSALIDASMED` PRIMARY KEY (`IDSALIDASMED`)
)
;

CREATE TABLE `SHENTRADASMED`
(
	`IDENTRADA` INT NOT NULL AUTO_INCREMENT,
	`FECHAENTRADA` DATE NOT NULL,
	`IDMEDICAMENTO` INT NOT NULL,
	`CANTIDAD` VARCHAR(10) NOT NULL,
	CONSTRAINT `PK_SHENTRADASMED` PRIMARY KEY (`IDENTRADA`)
)
;

CREATE TABLE `SHMEDICAMENTOS`
(
	`IDMEDICAMENTOS` INT NOT NULL AUTO_INCREMENT,
	`ADESCRIPCIONMEDICAMENTO` VARCHAR(100) NOT NULL,
	`NCOSTO` DECIMAL(10,2) NOT NULL,
	`AUBICACI0N` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_SHMEDICAMENTOS` PRIMARY KEY (`IDMEDICAMENTOS`)
)
;

CREATE TABLE `SHCITASMEDICAS`
(
	`IDCITASMEDICAS` INT NOT NULL AUTO_INCREMENT,
	`IDCONSULTORIO` INT NOT NULL,
	`IDGSPERSONA` INT NOT NULL,
	`AFECHACONSULTA` DATE NOT NULL,
	`ARECETAMEDICA` TINYINT 	,
	`RECETAMEDICA` BLOB 	,
	CONSTRAINT `PK_SHCITASMEDICAS` PRIMARY KEY (`IDCITASMEDICAS`)
)
;

CREATE TABLE `SHCONSULTORIOS`
(
	`IDSHCONSULTORIOS` INT NOT NULL AUTO_INCREMENT,
	`AOFICINACONSULTORIO` VARCHAR(50) NOT NULL,
	`IDMEDICO` INT NOT NULL,
	CONSTRAINT `PK_SHCONSULTORIOS` PRIMARY KEY (`IDSHCONSULTORIOS`)
)
;

CREATE TABLE `SHMEDICOSASIGNADOS`
(
	`IDMEDICO` INT NOT NULL AUTO_INCREMENT,
	`IDGSPERSONA` INT NOT NULL,
	`AESPECIALIDAD` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_SHMEDICOSASIGNADOS` PRIMARY KEY (`IDMEDICO`)
)
;

CREATE TABLE `SHPROCESOS`
(
	`IDSHPROCESOS` INT NOT NULL AUTO_INCREMENT,
	`APROCESO` VARCHAR(100) NOT NULL,
	`IDDIRECCIONEMP` INT NOT NULL,
	`IDGSAREASDIRECCION` INT NOT NULL,
	`AFECHAINICIO` DATE NOT NULL,
	`AFECHAFIN` DATE NOT NULL,
	`AMANUALPROCESO` BLOB NOT NULL,
	CONSTRAINT `PK_SHPROCESOS` PRIMARY KEY (`IDSHPROCESOS`)
)
;

CREATE TABLE `INCURSOSXEMPL`
(
	`IDMICURSOSXEMPL` INT NOT NULL AUTO_INCREMENT,
	`IDGSPERSONAS` INT NOT NULL,
	`IDMICALENDARIOCURSOS` INT NOT NULL,
	CONSTRAINT `PK_INCURSOSXEMPL` PRIMARY KEY (`IDMICURSOSXEMPL`)
)
;

CREATE TABLE `MINCURSOS`
(
	`IDCURSOIND` INT NOT NULL AUTO_INCREMENT,
	`ANOMBRECURSO` VARCHAR(50) NOT NULL,
	`ATIPOCURSO` VARCHAR(20) NOT NULL,
	`IDGSDIRECCION` INT NOT NULL,
	`ACONTENIDO` VARCHAR(2500) 	,
	`AIMGFOLLETO` LONGBLOB NOT NULL,
	CONSTRAINT `PK_MINCURSOS` PRIMARY KEY (`IDCURSOIND`)
)
;

CREATE TABLE `GSAREASDIRECCION`
(
	`IDGSAREASDIRECCION` INT NOT NULL AUTO_INCREMENT,
	`ANOMBREAREA` VARCHAR(100) NOT NULL,
	`IDGSDIRECCION` INT NOT NULL,
	`IDGSPERSONAS` INT NOT NULL,
	CONSTRAINT `PK_IDGSAREASDIRECCION` PRIMARY KEY (`IDGSAREASDIRECCION`)
)
;

CREATE TABLE `GSPERFILESSISTEMA`
(
	`IDGESPERFILES` INT NOT NULL AUTO_INCREMENT,
	`ADESCRIPCION` VARCHAR(50) NOT NULL,
	`ACLAVEPERFIL` VARCHAR(10) NOT NULL,
	`AUFECHAMOV` DATETIME(0) 	,
	`AUIDUSUARIO` INT 	,
	`AUHORA` TIMESTAMP(0) 	,
	CONSTRAINT `PK_GSPERFILESSISTEMA` PRIMARY KEY (`IDGESPERFILES`)
)
;

CREATE TABLE `GSUSUARIOS`
(
	`IDGSUSUARIO` INT NOT NULL AUTO_INCREMENT,
	`IDGSPERSONAS` INT 	,
	`ACLAVEUSUARIO` VARCHAR(50) NOT NULL,
	`APASSWORD` VARCHAR(50) NOT NULL,
	`ACLAVEPERFIL` INT NOT NULL,
	CONSTRAINT `PK_GSUSUARIOS` PRIMARY KEY (`IDGSUSUARIO`)
)
;

CREATE TABLE `MICALENDARIOCURSOS`
(
	`IDMICALENDARCURSO` INT NOT NULL AUTO_INCREMENT,
	`IDCURSOIND` INT NOT NULL,
	`AFECHAINICIO` DATETIME(0) 	,
	`AFECHAFIN` DATETIME(0) NOT NULL,
	`ACOMENTARIOS` VARCHAR(250) 	,
	`ACLAVECURSO` VARCHAR(20) NOT NULL,
	`IDCAPACITADORES` INT 	,
	CONSTRAINT `PK_MICALENDARIOCURSOS` PRIMARY KEY (`IDMICALENDARCURSO`)
)
;

CREATE TABLE `GSPERFILESPUESTOS`
(
	`IDPERFILDEPUESTO` INT NOT NULL AUTO_INCREMENT,
	`IDGSPUESTOS` INT NOT NULL,
	`IDGSDIRECCION` INT 	,
	`AGERENCIAPERT` VARCHAR(50) 	,
	`APUESTOREPORTA` VARCHAR(20) 	,
	`ANIVELIMPACTO` VARCHAR(10) NOT NULL,
	`ANIVELEVALUACION` VARCHAR(10) NOT NULL,
	`ARANGOSUELDO` VARCHAR(50) NOT NULL,
	`NSUELDO` NUMERIC(10,2) NOT NULL,
	`AMISION` VARCHAR(500) NOT NULL,
	`NRANGOEDAD` VARCHAR(50) NOT NULL,
	`AGENERO` VARCHAR(50) NOT NULL,
	`AESTADOCIVIL` VARCHAR(20) 	,
	`AESCOLARIDAD` INT 	,
	`AESTATUSESCOLARIDAD` VARCHAR(20) 	,
	`NAEXPERIENCIA` VARCHAR(10) NOT NULL,
	`APUESTOSOCUPADOS` VARCHAR(150) NOT NULL,
	`ACONOCIMIENTOSTEC` VARCHAR(150) NOT NULL,
	`AIDIOMAS` VARCHAR(10) NOT NULL,
	`APROGRAMASINFO` VARCHAR(100) NOT NULL,
	`AMANEJOVALORES` VARCHAR(50) NOT NULL,
	`AHABILIDADESPRF` VARCHAR(150) NOT NULL,
	`AFUNESPECIFICAS` VARCHAR(500) 	,
	`AUFECHAMOV` DATETIME(0) NOT NULL,
	`AUIDGSUSUARIO` INT 	,
	`AUHORA` TIMESTAMP(0) 	,
	CONSTRAINT `PK_GSPERFILES` PRIMARY KEY (`IDPERFILDEPUESTO`)
)
;

CREATE TABLE `GSDIRECCIONESSUB`
(
	`IDGSDIRECCION` INT NOT NULL AUTO_INCREMENT,
	`ANOMBREDIRECCION` VARCHAR(50) NOT NULL,
	`IDGSPERSONAS` INT NOT NULL,
	`IDGSDIRDIRECCION` INT NOT NULL,
	CONSTRAINT `PK_GSDIRECCIONES` PRIMARY KEY (`IDGSDIRECCION`)
)
;

CREATE TABLE `GSPERSONAS`
(
	`IDGSPERSONAS` INT NOT NULL AUTO_INCREMENT,
	`ANOMBREPERSONA` VARCHAR(50) 	,
	`APATERNO` VARCHAR(20) 	,
	`AMATERNO` VARCHAR(20) 	,
	`ADIRECCION` VARCHAR(20) 	,
	`ATELEFONO` VARCHAR(20) 	,
	`ACURP` VARCHAR(50) 	,
	`ARFC` VARCHAR(20) 	,
	`AFECHANACIMIENTO` DATETIME(0) 	,
	`NCIUDAD` INT 	,
	`AESTADO` INT 	,
	`CVVTAE` BLOB 	,
	`CONTRATO` BLOB 	,
	`IDGSPUESTOS` INT 	,
	`ACANDIDATO` TINYINT 	,
	`AEMPLEADO` TINYINT 	,
	`ADRESULTPSICO` BLOB 	,
	`AUFECHAMOV` DATETIME(0) 	,
	`IDUSUARIO` INT 	,
	`AUHORA` TIMESTAMP(0) 	,
	CONSTRAINT `PK_GS_PERSONAS` PRIMARY KEY (`IDGSPERSONAS`)
)
;

CREATE TABLE `GSDIRDIRECCIONESGEN`
(
	`IDGSDIRDIRECCION` INT NOT NULL AUTO_INCREMENT,
	`ACLAVEDIRECCION` VARCHAR(10) NOT NULL,
	`ANOMBREDIRECCION` VARCHAR(50) NOT NULL,
	`IDGSPERSONAS` INT NOT NULL,
	CONSTRAINT `PK_GSDIRDIRECCIONES` PRIMARY KEY (`IDGSDIRDIRECCION`)
)
;

CREATE TABLE `GSGERENCIAS`
(
	`IDGSGERENCIAS` INT NOT NULL AUTO_INCREMENT,
	`ADESCRIPCIONGERE` VARCHAR(50) NOT NULL,
	`IDGSPERSONA` INT NOT NULL,
	`IDGSPERSONAS` INT 	,
	CONSTRAINT `PK_GSGERENCIAS` PRIMARY KEY (`IDGSGERENCIAS`)
)
;

CREATE TABLE `GSPUESTOS`
(
	`IDGSPUESTOS` INT NOT NULL AUTO_INCREMENT,
	`ANOMBREPUESTO` VARCHAR(50) NOT NULL,
	`ADESCRIPCIONPUESTO` VARCHAR(100) 	,
	CONSTRAINT `PK_GSPUESTOS` PRIMARY KEY (`IDGSPUESTOS`)
)
;

CREATE TABLE `MICAPACITADORES`
(
	`IDCAPACITADORES` INT NOT NULL AUTO_INCREMENT,
	`IDGSPERSONA` INT NOT NULL,
	`APREPARACION` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_MICAPACITADORES` PRIMARY KEY (`IDCAPACITADORES`)
)
;

ALTER TABLE `SHSALIDASMED` 
 ADD CONSTRAINT `FK_SHSALIDASMED_SHCONSULTORIOS`
	FOREIGN KEY (`IDCONSULTORIO`) REFERENCES `SHCONSULTORIOS` (`IDSHCONSULTORIOS`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `SHSALIDASMED` 
 ADD CONSTRAINT `FK_SHSALIDASMED_SHMEDICAMENTOS`
	FOREIGN KEY (`IDMEDICAMENTO`) REFERENCES `SHMEDICAMENTOS` (`IDMEDICAMENTOS`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `SHENTRADASMED` 
 ADD CONSTRAINT `FK_SHENTRADASMED_SHMEDICAMENTOS`
	FOREIGN KEY (`IDMEDICAMENTO`) REFERENCES `SHMEDICAMENTOS` (`IDMEDICAMENTOS`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `SHCITASMEDICAS` 
 ADD CONSTRAINT `FK_SHCITASMEDICAS_GSPERSONAS`
	FOREIGN KEY (`IDGSPERSONA`) REFERENCES `GSPERSONAS` (`IDGSPERSONAS`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `SHCITASMEDICAS` 
 ADD CONSTRAINT `FK_SHCITASMEDICAS_SHCONSULTORIOS`
	FOREIGN KEY (`IDCONSULTORIO`) REFERENCES `SHCONSULTORIOS` (`IDSHCONSULTORIOS`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `SHCONSULTORIOS` 
 ADD CONSTRAINT `FK_SHCONSULTORIOS_SHMEDICOSASIGNADOS`
	FOREIGN KEY (`IDMEDICO`) REFERENCES `SHMEDICOSASIGNADOS` (`IDMEDICO`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `SHMEDICOSASIGNADOS` 
 ADD CONSTRAINT `FK_SHMEDICOSASIGNADOS_GSPERSONAS`
	FOREIGN KEY (`IDGSPERSONA`) REFERENCES `GSPERSONAS` (`IDGSPERSONAS`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `INCURSOSXEMPL` 
 ADD CONSTRAINT `FK_INCURSOSXEMPL_GSPERSONAS`
	FOREIGN KEY (`IDGSPERSONAS`) REFERENCES `GSPERSONAS` (`IDGSPERSONAS`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `INCURSOSXEMPL` 
 ADD CONSTRAINT `FK_INCURSOSXEMPL_MICALENDARIOCURSOS`
	FOREIGN KEY (`IDMICALENDARIOCURSOS`) REFERENCES `MICALENDARIOCURSOS` (`IDMICALENDARCURSO`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `MINCURSOS` 
 ADD CONSTRAINT `FK_MINCURSOS_GSDIRECCIONESSUB`
	FOREIGN KEY (`IDGSDIRECCION`) REFERENCES `GSDIRECCIONESSUB` (`IDGSDIRECCION`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `GSAREASDIRECCION` 
 ADD CONSTRAINT `FK_GSAREASDIRECCION_GSDIRECCIONESSUB`
	FOREIGN KEY (`IDGSDIRECCION`) REFERENCES `GSDIRECCIONESSUB` (`IDGSDIRECCION`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `MICALENDARIOCURSOS` 
 ADD CONSTRAINT `FK_MICALENDARIOCURSOS_MICAPACITADORES`
	FOREIGN KEY (`IDCAPACITADORES`) REFERENCES `MICAPACITADORES` (`IDCAPACITADORES`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `MICALENDARIOCURSOS` 
 ADD CONSTRAINT `FK_MICALENDARIOCURSOS_MINCURSOS`
	FOREIGN KEY (`IDCURSOIND`) REFERENCES `MINCURSOS` (`IDCURSOIND`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `GSPERFILESPUESTOS` 
 ADD CONSTRAINT `FK_GSPERFILESPUESTOS_GSDIRECCIONES`
	FOREIGN KEY (`IDGSDIRECCION`) REFERENCES `GSDIRECCIONESSUB` (`IDGSDIRECCION`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `GSPERFILESPUESTOS` 
 ADD CONSTRAINT `FK_GSPERFILESPUESTOS_GSPUESTOS`
	FOREIGN KEY (`IDGSPUESTOS`) REFERENCES `GSPUESTOS` (`IDGSPUESTOS`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `GSDIRECCIONESSUB` 
 ADD CONSTRAINT `FK_GSDIRECCIONESSUB_GSDIRDIRECCIONESGEN`
	FOREIGN KEY (`IDGSDIRDIRECCION`) REFERENCES `GSDIRDIRECCIONESGEN` (`IDGSDIRDIRECCION`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `GSDIRECCIONESSUB` 
 ADD CONSTRAINT `FK_GSDIRECCIONESSUB_GSPERSONAS`
	FOREIGN KEY (`IDGSPERSONAS`) REFERENCES `GSPERSONAS` (`IDGSPERSONAS`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `GSPERSONAS` 
 ADD CONSTRAINT `FK_GSPERSONAS_GSPUESTOS`
	FOREIGN KEY (`IDGSPUESTOS`) REFERENCES `GSPUESTOS` (`IDGSPUESTOS`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `GSDIRDIRECCIONESGEN` 
 ADD CONSTRAINT `FK_GSDIRDIRECCIONESGEN_GSPERSONAS`
	FOREIGN KEY (`IDGSPERSONAS`) REFERENCES `GSPERSONAS` (`IDGSPERSONAS`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `GSGERENCIAS` 
 ADD CONSTRAINT `FK_GSGERENCIAS_GSPERSONAS`
	FOREIGN KEY (`IDGSPERSONAS`) REFERENCES `GSPERSONAS` (`IDGSPERSONAS`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `MICAPACITADORES` 
 ADD CONSTRAINT `FK_MICAPACITADORES_GSPERSONAS`
	FOREIGN KEY (`IDGSPERSONA`) REFERENCES `GSPERSONAS` (`IDGSPERSONAS`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
